### ISSUE TITLE
If we need a 3/4 column?

### ISSUE THREAD

**Issue by equinusocio** [timhecker/sass-mixin-flex-grid#1]
I want the first `my-grid__item` to be 3/4 of the parent width, how i can handle this situation?

```html
<div class="my-grid">
   <div class="my-grid__item"></div>
   <div class="my-grid__item"></div>
</div>
```

**Comment by timhecker** [comment]
This mixin works only with equal cols at the moment. Sorry ;)

**Comment by equinusocio** [comment]
Le griglie sono morte :D
